using System.Text.Json.Serialization;

namespace Heimdall.Contracts;

/// <summary>AOT-friendly source-generated serialization for all wire contracts. camelCase on the wire.</summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(MetricBatchRequest))]
[JsonSerializable(typeof(IngestResponse))]
[JsonSerializable(typeof(HostMetricsResponse))]
[JsonSerializable(typeof(IReadOnlyList<HostSummaryDto>))]
[JsonSerializable(typeof(EnrollRequest))]
[JsonSerializable(typeof(EnrollResponse))]
[JsonSerializable(typeof(CreateHealthCheckRequest))]
[JsonSerializable(typeof(HealthCheckStatusDto))]
[JsonSerializable(typeof(IReadOnlyList<HealthCheckStatusDto>))]
[JsonSerializable(typeof(HealthCheckHistoryResponse))]
[JsonSerializable(typeof(OverviewSnapshot))]
[JsonSerializable(typeof(CreateAlertRuleRequest))]
[JsonSerializable(typeof(AlertRuleDto))]
[JsonSerializable(typeof(IReadOnlyList<AlertRuleDto>))]
[JsonSerializable(typeof(IReadOnlyList<AlertDto>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(SetupRequest))]
[JsonSerializable(typeof(AuthStatusResponse))]
[JsonSerializable(typeof(CreateServerRequest))]
[JsonSerializable(typeof(ServerDto))]
[JsonSerializable(typeof(IReadOnlyList<ServerDto>))]
[JsonSerializable(typeof(ServerLinkDto))]
[JsonSerializable(typeof(IReadOnlyList<ServerLinkDto>))]
[JsonSerializable(typeof(CreateServerLinkRequest))]
[JsonSerializable(typeof(InventoryResponse))]
[JsonSerializable(typeof(InventoryReportRequest))]
[JsonSerializable(typeof(IReadOnlyList<ChannelStatusDto>))]
[JsonSerializable(typeof(TestNotificationResult))]
public sealed partial class HeimdallJsonContext : JsonSerializerContext;
